// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPb87MBK0sp-Rp_xjMDPCucT3HObYOzbE',
    appId: '1:292577237197:android:c7559319f1dee8b9b87184',
    messagingSenderId: '292577237197',
    projectId: 'complaint-manage-sys',
    storageBucket: 'complaint-manage-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpF6isKZ4174_STNubNfV8M8b0NIXiOuo',
    appId: '1:292577237197:ios:e438f33180c3d2efb87184',
    messagingSenderId: '292577237197',
    projectId: 'complaint-manage-sys',
    storageBucket: 'complaint-manage-sys.appspot.com',
    iosBundleId: 'com.example.complaintManagementSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuWQ-L_hWVd6qKPRxGuCcHBjEPP4ChVtA',
    appId: '1:292577237197:web:eb3590d01277eb2eb87184',
    messagingSenderId: '292577237197',
    projectId: 'complaint-manage-sys',
    authDomain: 'complaint-manage-sys.firebaseapp.com',
    storageBucket: 'complaint-manage-sys.appspot.com',
    measurementId: 'G-8NQYYRRHNW',
  );
}
